import React from "react";

export const rightDrawerWidth = 300;
export const bottomDrawerHeight = 240;
export const leftDrawerWidth = 300;

export const OFFSET = 200;
export const VIEWPORT_WIDTH = 810;
export const VIEWPORT_HEIGHT = 540;

export const SPRITES_BY_CATEGORY_TO_SVG_ELEMENT_MAP = {
  "Immune cells": {
    "B cell": {
      name: "B cell",
      tags: [
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody",
        "antigen",
        "cell",
        "humoral immunity",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "naive cell",
        "receptor",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    Basophil: {
      name: "Basophil",
      tags: [
        "allergy",
        "cell",
        "degranulation",
        "granulocyte",
        "histamine",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Dendritic cell": {
      name: "Dendritic cell",
      tags: [
        "APC",
        "antigen",
        "antigen presenting cell",
        "cell",
        "dendritic cell",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "maturation",
        "migration",
        "myeloid",
        "presentation",
        "presenting",
        "T cell activation",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Dendritic cell (immature)": {
      name: "Dendritic cell (immature)",
      tags: [
        "APC",
        "antigen",
        "antigen presenting cell",
        "cell",
        "dendritic cell",
        "immature",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "migration",
        "myeloid",
        "presentation",
        "presenting",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Dendritic cell (mature)": {
      name: "Dendritic cell (mature)",
      tags: [
        "APC",
        "antigen",
        "antigen presenting cell",
        "cell",
        "dendritic cell",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "mature",
        "migration",
        "myeloid",
        "presentation",
        "presenting",
        "T cell activation",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    Eosinophil: {
      name: "Eosinophil",
      tags: [
        "allergy",
        "cell",
        "degranulation",
        "eosinophil",
        "granulocyte",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "parasite",
        "parasitic",
        "parasitic infection",
        "myeloid",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Follicular dendritic cell": {
      name: "Follicular dendritic cell",
      tags: [
        "APC",
        "antigen",
        "antigen presenting cell",
        "cell",
        "dendritic cell",
        "follicle",
        "follicular",
        "germinal center",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "presentation",
        "presenting",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    Macrophage: {
      name: "Macrophage",
      tags: [
        "APC",
        "antigen",
        "antigen presenting cell",
        "cell",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "macrophage",
        "myeloid",
        "phagocyte",
        "phagocytosis",
        "presenting",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Macrophage (phagocytosis)": {
      name: "Macrophage (phagocytosis)",
      tags: [
        "APC",
        "antigen",
        "antigen presenting cell",
        "cell",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "macrophage",
        "myeloid",
        "phagocyte",
        "phagocytosis",
        "presenting",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Mast cell": {
      name: "Mast cell",
      tags: [
        "mast cell",
        "adaptive",
        "allergy",
        "cell",
        "degranulation",
        "granulocyte",
        "histamine",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Mast cell (degranulating)": {
      name: "Mast cell (degranulating)",
      tags: [
        "mast cell",
        "allergy",
        "cell",
        "degranulation",
        "granulocyte",
        "histamine",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    Microglia: {
      name: "Microglia",
      tags: [
        "APC",
        "antigen presenting cell",
        "brain",
        "cell",
        "CNS",
        "central nervous system",
        "glia",
        "glium",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "microglia",
        "microglial cell",
        "myeloid",
        "nervous system",
        "neuroinflammation",
        "phagocytosis",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Microglia (immature)": {
      name: "Microglia (immature)",
      tags: [
        "APC",
        "antigen presenting cell",
        "brain",
        "cell",
        "CNS",
        "central nervous system",
        "glia",
        "glium",
        "immature",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "microglia",
        "microglial cell",
        "myeloid",
        "nervous system",
        "neuroinflammation",
        "phagocytosis",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    Monocyte: {
      name: "Monocyte",
      tags: [
        "APC",
        "antigen presenting cell",
        "cell",
        "circulation",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "monocyte",
        "myeloid",
        "phagocyte",
        "phagocytosis",
        "presenting",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Naive B cell": {
      name: "Naive B cell",
      tags: [
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody",
        "antigen",
        "cell",
        "humoral immunity",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "naive",
        "naive cell",
        "receptor",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Naive T cell": {
      name: "Naive T cell",
      tags: [
        "CD4",
        "CD8",
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "naive",
        "naive cell",
        "receptor",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Natural killer cell": {
      name: "Natural killer cell",
      tags: [
        "NK",
        "cell",
        "cytotoxic",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "lymphocyte",
        "natural killer",
        "receptor",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    Neutrophil: {
      name: "Neutrophil",
      tags: [
        "cell",
        "chemotaxis",
        "degranulation",
        "granulocyte",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "neutrophil",
        "phagocyte",
        "phagocytosis",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (crawling)": {
      name: "Neutrophil (crawling)",
      tags: [
        "cell",
        "chemotaxis",
        "crawling",
        "degranulation",
        "granulocyte",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "neutrophil",
        "phagocyte",
        "phagocytosis",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (diapedesis)": {
      name: "Neutrophil (diapedesis)",
      tags: [
        "cell",
        "chemotaxis",
        "degranulation",
        "diapedesis",
        "extravasation",
        "granulocyte",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "neutrophil",
        "phagocyte",
        "phagocytosis",
        "transmigration",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (migrating)": {
      name: "Neutrophil (migrating)",
      tags: [
        "cell",
        "chemotaxis",
        "degranulation",
        "granulocyte",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "migration",
        "migrating",
        "myeloid",
        "neutrophil",
        "phagocyte",
        "phagocytosis",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (NETosis)": {
      name: "Neutrophil (NETosis)",
      tags: [
        "cell",
        "degranulation",
        "granulocyte",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "NET",
        "NETosis",
        "neutrophil",
        "neutrophil extracellular trap",
        "phagocyte",
        "phagocytosis",
        "trap",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neutrophil (phagocytosing)": {
      name: "Neutrophil (phagocytosing)",
      tags: [
        "cell",
        "degranulation",
        "granulocyte",
        "immune",
        "immunity",
        "innate",
        "innate immunity",
        "leukocyte",
        "myeloid",
        "neutrophil",
        "phagocyte",
        "phagocytosis",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Plasma cell": {
      name: "Plasma cell",
      tags: [
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody",
        "antigen",
        "cell",
        "differentiated",
        "humoral immunity",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "plasma cell",
        "receptor",
        "secretion",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    Plasmablast: {
      name: "Plasmablast",
      tags: [
        "B cell",
        "adaptive",
        "adaptive immunity",
        "antibody",
        "antigen",
        "cell",
        "differentiating",
        "humoral immunity",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "plasmablast",
        "receptor",
        "secretion",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell": {
      name: "T cell",
      tags: [
        "CD4",
        "CD8",
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "receptor",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell (attacking)": {
      name: "T cell (attacking)",
      tags: [
        "CD8",
        "T cell",
        "adaptive",
        "adaptive immunity",
        "attack",
        "attacking",
        "cell",
        "cytotoxic",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "receptor",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell (cytokine release)": {
      name: "T cell (cytokine release)",
      tags: [
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "cytokine",
        "cytokine release",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "receptor",
        "release",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "T cell (migrating)": {
      name: "T cell (migrating)",
      tags: [
        "T cell",
        "adaptive",
        "adaptive immunity",
        "cell",
        "immune",
        "immunity",
        "leukocyte",
        "lymphocyte",
        "migration",
        "migrating",
        "receptor",
        "white blood cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
  },
  "Lab animals": {
    Fish: {
      name: "Fish",
      tags: [
        "animal",
        "aquatic",
        "fish",
        "lab",
        "lab animal",
        "model organism",
        "zebrafish",
      ],
    },
    Mosquito: {
      name: "Mosquito",
      tags: [
        "animal",
        "arthropod",
        "disease vector",
        "entomology",
        "insect",
        "lab",
        "lab animal",
        "mosquito",
        "vector",
      ],
    },
    "Mosquito (superior)": {
      name: "Mosquito (superior)",
      tags: [
        "animal",
        "arthropod",
        "disease vector",
        "entomology",
        "insect",
        "lab",
        "lab animal",
        "mosquito",
        "superior view",
        "top view",
        "vector",
      ],
    },
    Mouse: {
      name: "Mouse",
      tags: [
        "animal",
        "lab",
        "lab animal",
        "model organism",
        "mouse",
        "murine",
        "rodent",
      ],
      variants: ["black", "grey", "white"],
    },
  },
  "Lab icons": {
    Microscope: {
      name: "Microscope",
      tags: [
        "equipment",
        "icon",
        "lab",
        "lab icon",
        "microscope",
        "research",
        "science",
        "tool",
      ],
    },
    "Petri dish": {
      name: "Petri dish",
      tags: [
        "agar",
        "culture",
        "dish",
        "equipment",
        "icon",
        "lab",
        "lab icon",
        "microbiology",
        "petri dish",
        "plate",
        "science",
        "tool",
      ],
    },
    Pipette: {
      name: "Pipette",
      tags: [
        "equipment",
        "icon",
        "lab",
        "lab icon",
        "liquid handling",
        "pipette",
        "science",
        "tool",
        "volume",
      ],
    },
  },
  Organs: {
    Brain: {
      name: "Brain",
      tags: [
        "brain",
        "CNS",
        "central nervous system",
        "nervous system",
        "neuro",
        "organ",
      ],
    },
    Heart: {
      name: "Heart",
      tags: [
        "cardiac",
        "cardiovascular",
        "circulatory system",
        "heart",
        "organ",
      ],
    },
    "Human (outline)": {
      name: "Human (outline)",
      tags: ["anatomy", "body", "human", "outline", "organ", "silhouette"],
    },
    "Human arm": {
      name: "Human arm",
      tags: ["anatomy", "arm", "human", "limb", "musculoskeletal", "organ"],
    },
    "Human leg": {
      name: "Human leg",
      tags: ["anatomy", "human", "leg", "limb", "musculoskeletal", "organ"],
    },
    Intestine: {
      name: "Intestine",
      tags: [
        "digestive",
        "gastrointestinal",
        "GI tract",
        "gut",
        "intestine",
        "organ",
      ],
    },
    Kidney: {
      name: "Kidney",
      tags: ["excretory", "kidney", "nephrology", "organ", "renal", "urinary"],
    },
    Liver: {
      name: "Liver",
      tags: ["detoxification", "hepatic", "liver", "metabolism", "organ"],
    },
    Lung: {
      name: "Lung",
      tags: [
        "breathing",
        "gas exchange",
        "lung",
        "organ",
        "pulmonary",
        "respiratory",
      ],
    },
    "Lymph node": {
      name: "Lymph node",
      tags: ["immune", "immunity", "lymph", "lymph node", "lymphatic", "organ"],
    },
    "Lymph node (vascularised)": {
      name: "Lymph node (vascularised)",
      tags: [
        "immune",
        "immunity",
        "lymph",
        "lymph node",
        "lymphatic",
        "organ",
        "vascularised",
        "vascularized",
        "vasculature",
      ],
    },
    Spleen: {
      name: "Spleen",
      tags: ["blood", "immune", "immunity", "organ", "spleen"],
    },
  },
  "Structural cells": {
    "Apoptotic cancer cell": {
      name: "Apoptotic cancer cell",
      tags: [
        "apoptosis",
        "apoptotic",
        "cancer",
        "cell",
        "death",
        "dying",
        "oncology",
        "programmed cell death",
        "structural cell",
        "tumor",
        "tumour",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Apoptotic cell": {
      name: "Apoptotic cell",
      tags: [
        "apoptosis",
        "apoptotic",
        "cell",
        "death",
        "dying",
        "programmed cell death",
        "structural cell",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Collagen fibres": {
      name: "Collagen fibres",
      tags: [
        "collagen",
        "collagen fibers",
        "collagen fibres",
        "ECM",
        "extracellular matrix",
        "fibers",
        "fibres",
        "matrix",
        "structural cell",
        "tissue",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Collagen fibres (dense)": {
      name: "Collagen fibres (dense)",
      tags: [
        "collagen",
        "collagen fibers",
        "collagen fibres",
        "dense",
        "ECM",
        "extracellular matrix",
        "matrix",
        "structural cell",
        "tissue",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Endothelial cell": {
      name: "Endothelial cell",
      tags: [
        "angiogenesis",
        "blood vessel",
        "capillary",
        "cell",
        "endothelial",
        "endothelium",
        "epithelium",
        "lining",
        "structural cell",
        "vasculature",
        "vessel",
      ],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Endothelial cell 2": {
      name: "Endothelial cell 2",
      tags: [
        "barrier",
        "cell",
        "endothelial",
        "endothelium",
        "epithelium",
        "lining",
        "mucosa",
        "mucosal",
        "structural cell",
        "tissue",
      ],
      variants: ["beige", "peach", "pink", "red"],
    },
    "Epithelial cell": {
      name: "Epithelial cell",
      tags: [
        "barrier",
        "cell",
        "epithelial",
        "epithelium",
        "lining",
        "mucosa",
        "mucosal",
        "structural cell",
        "tissue",
      ],
      variants: ["beige", "peach", "pink", "red"],
    },
    Fibroblast: {
      name: "Fibroblast",
      tags: [
        "cell",
        "ECM",
        "extracellular matrix",
        "fibroblast",
        "matrix",
        "structural cell",
        "tissue",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Fibroblast (activated)": {
      name: "Fibroblast (activated)",
      tags: [
        "activated",
        "cell",
        "ECM",
        "extracellular matrix",
        "fibroblast",
        "matrix",
        "myofibroblast",
        "structural cell",
        "tissue",
      ],
      variants: ["blue", "green", "grey", "orange", "purple", "red", "yellow"],
    },
    "Neuron (degrading)": {
      name: "Neuron (degrading)",
      tags: [
        "axon",
        "CNS",
        "central nervous system",
        "degeneration",
        "degrading",
        "demyelination",
        "neuro",
        "neuron",
        "neurodegeneration",
        "nervous system",
        "structural cell",
        "synapse",
      ],
    },
    "Neuron (sheathed)": {
      name: "Neuron (sheathed)",
      tags: [
        "axon",
        "CNS",
        "central nervous system",
        "demyelination",
        "myelin",
        "myelinated",
        "neuro",
        "neuron",
        "nervous system",
        "oligodendrocyte",
        "PNS",
        "peripheral nervous system",
        "structural cell",
        "synapse",
      ],
    },
    Neuron: {
      name: "Neuron",
      tags: [
        "axon",
        "CNS",
        "central nervous system",
        "dendrite",
        "neuro",
        "neuron",
        "nervous system",
        "PNS",
        "peripheral nervous system",
        "structural cell",
        "synapse",
      ],
    },
    Platelets: {
      name: "Platelets",
      tags: [
        "blood",
        "clot",
        "clotting",
        "coagulation",
        "hemostasis",
        "platelet",
        "platelets",
        "structural cell",
        "thrombocyte",
        "thrombosis",
      ],
      variants: ["grey", "yellow"],
    },
    "Red blood cell (bursting)": {
      name: "Red blood cell (bursting)",
      tags: [
        "blood",
        "bursting",
        "cell",
        "erythrocyte",
        "hemolysis",
        "lysis",
        "RBC",
        "red blood cell",
        "structural cell",
      ],
    },
    "Red blood cell (lateral)": {
      name: "Red blood cell (lateral)",
      tags: [
        "biconcave",
        "blood",
        "cell",
        "erythrocyte",
        "RBC",
        "red blood cell",
        "side view",
        "structural cell",
      ],
    },
    "Red blood cell (superior)": {
      name: "Red blood cell (superior)",
      tags: [
        "biconcave",
        "blood",
        "cell",
        "erythrocyte",
        "RBC",
        "red blood cell",
        "structural cell",
        "top view",
      ],
    },
  },
} as const;

export const SPRITE_TO_SVG_ELEMENT_MAP: Record<
  string,
  { name: string; tags: string[]; category: string; variants?: string[] }
> = Object.fromEntries(
  Object.entries(SPRITES_BY_CATEGORY_TO_SVG_ELEMENT_MAP).flatMap(
    ([category, cells]) =>
      Object.entries(cells).map(([key, v]) => {
        const name = v.name || key;
        return [name, { ...v, category }];
      })
  )
);

// export const SPRITE_TO_SVG_ELEMENT_MAP = {
//   b_cell_1: { name: "B Cell 1", tags: ["Cell"], svg: <BCell1 id="b_cell_1" /> },
//   basophil: {
//     name: "Basophil",
//     tags: ["Cell"],
//     svg: <Basophil id="basophil" />,
//   },
//   dendritic_cell_1: {
//     name: "Dendritic Cell 1",
//     tags: [],
//     svg: <DendriticCell1 id="dendritic_cell_1" />,
//   },
//   dendritic_cell_2: {
//     name: "Dendritic Cell 2",
//     tags: [],
//     svg: <DendriticCell2 id="dendritic_cell_2" />,
//   },
//   t_cell_1: { name: "T Cell 1", tags: [], svg: <TCell1 id="t_cell_1" /> },
//   t_cell_2: { name: "T Cell 2", tags: [], svg: <TCell2 id="t_cell_2" /> },
//   fibroblast_1: {
//     name: "Fibroblast 1",
//     tags: [],
//     svg: <Fibroblast1 id="fibroblast_1" />,
//   },
//   macrophage_1: {
//     name: "Macrophage 1",
//     tags: [],
//     svg: <Macrophage1 id="macrophage_1" />,
//   },
//   mhc_class_i: {
//     name: "MHC Class I",
//     tags: [],
//     svg: <MhcClassI id="mhc_class_i" />,
//   },
//   mhc_class_ii: {
//     name: "MHC Class II",
//     tags: [],
//     svg: <MhcClassII id="mhc_class_ii" />,
//   },
//   monocyte: { name: "Monocyte", tags: [], svg: <Monocyte id="monocyte" /> },
//   natural_killer_cell_2: {
//     name: "Natural Killer Cell 2",
//     tags: [],
//     svg: <NaturalKillerCell2 id="natural_killer_cell_2" />,
//   },
//   natural_killer_cell: {
//     name: "Natural Killer Cell",
//     tags: [],
//     svg: <NaturalKillerCell id="natural_killer_cell" />,
//   },
//   neutrophil: {
//     name: "Neutrophil",
//     tags: [],
//     svg: <Neutrophil id="neutrophil" />,
//   },
//   TCR_1: { name: "TCR 1", tags: [], svg: <TCR1 id="TCR_1" /> },
//   TCR_2: { name: "TCR 2", tags: [], svg: <TCR2 id="TCR_2" /> },
//   BCR_IgA_Dimer: {
//     name: "BCR IgA Dimer",
//     tags: [],
//     svg: <BCRIgADimer id="BCR_IgA_Dimer" />,
//   },
//   BCR_IgA: { name: "BCR IgA", tags: [], svg: <BCRIgA id="BCR_IgA" /> },
//   BCR_IgD: { name: "BCR IgD", tags: [], svg: <BCRIgD id="BCR_IgD" /> },
//   BCR_IgE: { name: "BCR IgE", tags: [], svg: <BCRIgE id="BCR_IgE" /> },
//   BCR_IgE_2: { name: "BCR IgE 2", tags: [], svg: <BCRIgE2 id="BCR_IgE_2" /> },
//   BCR_IgG_flexible_1: {
//     name: "BCR IgG Flexible 1",
//     tags: [],
//     svg: <BCRIgGFlexible1 id="BCR_IgG_flexible_1" />,
//   },
//   BCR_IgG_flexible_2: {
//     name: "BCR IgG Flexible 2",
//     tags: [],
//     svg: <BCRIgGFlexible2 id="BCR_IgG_flexible_2" />,
//   },
//   BCR_IgG: { name: "BCR IgG", tags: [], svg: <BCRIgG id="BCR_IgG" /> },
//   BCR_IgM_monomer: {
//     name: "BCR IgM Monomer",
//     tags: [],
//     svg: <BCRIgMMonomer id="BCR_IgM_monomer" />,
//   },
//   BCR_IgM_pentamer: {
//     name: "BCR IgM Pentamer",
//     tags: [],
//     svg: <BCRIgMPentamer id="BCR_IgM_pentamer" />,
//   },
//   BCR_IgM_pentamer_2: {
//     name: "BCR IgM Pentamer 2",
//     tags: [],
//     svg: <BCRIgMPentamer2 id="BCR_IgM_pentamer_2" />,
//   },
//   upwork_cell_1: {
//     name: "Upwork Cell 1",
//     tags: [],
//     svg: <UpworkCell1 id="upwork_cells_1" />,
//   },
//   upwork_cell_3: {
//     name: "Upwork Cell 3",
//     tags: [],
//     svg: <UpworkCell3 id="upwork_cells_3" />,
//   },
//   upwork_cell_4: {
//     name: "Upwork Cell 4",
//     tags: [],
//     svg: <UpworkCell4 id="upwork_cells_4" />,
//   },
// } as const;
